"""ROCmBench Agent utilities."""

from .analysis import (
    analyze_benchmark,
    assess_gpu_saturation,
    build_deployment_gate_matrix,
    build_report,
    deployment_decision,
    estimate_costs,
    parse_rocm_monitor,
    parse_rocm_monitor_series,
    plan_next_experiments,
    summarize_impact,
)
from .production import (
    assess_regression,
    check_openai_endpoint,
    compare_payloads,
    ensure_ssh_tunnel,
    generate_production_artifacts,
    init_history,
    list_openai_endpoint_models,
    load_history,
    record_history,
    run_live_benchmark,
    save_payload,
    search_huggingface_models,
    start_remote_vllm_model,
)

__all__ = [
    "analyze_benchmark",
    "assess_gpu_saturation",
    "build_deployment_gate_matrix",
    "build_report",
    "deployment_decision",
    "estimate_costs",
    "parse_rocm_monitor",
    "parse_rocm_monitor_series",
    "plan_next_experiments",
    "summarize_impact",
    "assess_regression",
    "check_openai_endpoint",
    "compare_payloads",
    "ensure_ssh_tunnel",
    "generate_production_artifacts",
    "init_history",
    "list_openai_endpoint_models",
    "load_history",
    "record_history",
    "run_live_benchmark",
    "save_payload",
    "search_huggingface_models",
    "start_remote_vllm_model",
]
